### pre

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F)
library(hms)
library(readxl)
library(lubridate)
library(magrittr)
library(tidyverse)
library(data.table)
```

```{r}
# data <- read_excel('D:/tmp/canbu/cankao2.xlsx') %>%
data <- read_excel('cankao2.xlsx') %>%
  select(-1) %>%
  setnames(names(.), c(paste0('V', 1:ncol(.)))) %>%
  mutate_all(~str_replace_all(., '  \\r\\n', ':00')) %>%
  mutate_all(~str_replace_all(., '(\\d{2}:\\d{2}:00)\\s*\\S*(\\d{2}:\\d{2})', '\\$1\\$2:00')) %>%
  mutate_all(~str_replace_all(., '\\\\', '')) %>%
  mutate_all(
    ~ifelse(
      as.hms(str_sub(., 9, 16)) <= as.hms(str_sub(., 1, 8)),
      str_replace_all(., str_sub(., 9, 16), '24:00:00'), .
    )
  )
```
 
```{r}
data[49,'V29']
```

$\surd$第49行29列的上班打卡时间和下班打卡时间应该是'10:23:00'和'20:16:00'

### 2018-12-05 01:21:46


```{r}
data %>% 
    mutate(index = row_number()) %>% 
    gather(var,value,-index) %>% 
    # gather:
    # 数据量小，可操作
    # mutate_all 并行耗时
    mutate(
        begin_time = str_sub(value,1,8)
        ,end_time = str_sub(value,-8,-1)
    ) %>% 
    mutate(
        is_valid = 
            if (
                hms(end_time) > hms('20:00:00')
                & (
                  hms(end_time) - hms(begin_time) >= dhours(10)
                  | hms(begin_time) < hms('10:10:00')
                )
            )
                1
            else 
                0
    ) %>% 
    select(index,var,is_valid) %>% 
    spread(var,is_valid) %>% 
    select(names(data)) -> data_work
```

`A and (B or C)`

```{r}
data_work$V29[49]
```

### 2018-12-05 01:30:40

`as.hms`函数检查无误。

```{r}
data %>% 
    mutate(index = row_number()) %>% 
    gather(var,value,-index) %>% 
    # gather:
    # 数据量小，可操作
    # mutate_all 并行耗时
    mutate(
        begin_time = str_sub(value,1,8)
        ,end_time = str_sub(value,-8,-1)
    ) %>% 
    mutate(
        is_valid = 
            if (
                as.hms(end_time) >= as.hms('20:00:00')
                & (
                  difftime(as.hms(end_time),as.hms(begin_time)) >= 10
                  | as.hms(begin_time)  <= as.hms('10:10:00')
                )
            )
                1
            else 
                0
    ) %>% 
    select(index,var,is_valid) %>% 
    spread(var,is_valid) %>% 
    select(names(data)) -> data_work
```

`A and (B or C)`

```{r}
data_work$V29[49]
```

### 2018-12-05 01:39:11

```{r}
data_work <- 
  data %>%
  mutate_all(
    ~if_else(
      # (as.hms(str_sub(., 9, 16)) >= as.hms('20:00:00')    # 下班打卡时间在 20:00 之后
      # & 
          difftime(as.hms(str_sub(., 9, 16)), as.hms(str_sub(., 1, 8))) >= 10
          # ) # 时间差 ≥10 小时
      
      # | (as.hms(str_sub(., 9, 16)) >= as.hms('20:00:00')  # 下班打卡时间在 20:00 之后
      # & as.hms(str_sub(., 1, 8))  <= as.hms('10:10:00')) # 上班打卡时间在 10:10 之前 
      ,1, 0
    )
  )

data$V29[49]
data_work$V29[49]
```

```{r}
if_else(
    difftime(as.hms(str_sub("10:23:0020:16:00", 9, 16)), as.hms(str_sub("10:23:0020:16:00", 1, 8))) >= 10
    ,1,0
)
```

```{r}
data %>% 
    select(V29) %>%
    .$V29 %>%
    # head(50) %>% 
    paste0('"',.,'"',collapse = ',') %>% cat
    # slice(1:50) %>%
    # head(49) %>% 
  mutate_all(
    ~if_else(
      # (as.hms(str_sub(., 9, 16)) >= as.hms('20:00:00')    # 下班打卡时间在 20:00 之后
      # & 
          difftime(as.hms(str_sub(., 9, 16)), as.hms(str_sub(., 1, 8))) >= 10
          # ) # 时间差 ≥10 小时
      
      # | (as.hms(str_sub(., 9, 16)) >= as.hms('20:00:00')  # 下班打卡时间在 20:00 之后
      # & as.hms(str_sub(., 1, 8))  <= as.hms('10:10:00')) # 上班打卡时间在 10:10 之前 
      ,1, 0
    )
  )
```

主要问题是这个函数导致`V29`都等于1

```{r}
c(
"NA","NA","NA","NA","NA","NA","NA","09:28:0018:44:00","10:09:0018:11:00","09:40:0018:45:00","NA","NA","09:12:0018:13:00","NA","NA","NA","NA","NA","NA","08:56:0020:30:00","NA","NA","10:13:0019:04:00","09:35:0018:48:00","09:40:0020:13:00","09:51:0018:00:00","09:33:0019:39:00","08:56:0020:20:00","10:00:0019:34:00","NA","09:45:0019:06:00","09:39:0018:58:00","09:41:0018:45:00","09:36:0019:20:00","09:13:0018:00:00","09:34:0019:30:00","09:50:0022:27:00","09:45:0022:51:00","09:12:0019:18:00","10:01:0019:17:00","09:55:0019:25:00","09:31:0019:35:00","09:43:0018:59:00","09:57:0018:32:00","09:29:0018:48:00","NA","09:51:0019:15:00","10:00:0019:04:00","10:23:0020:16:00","09:33:0020:23:00","NA","09:51:0019:26:00","10:04:0022:21:00","09:51:0019:15:00","09:57:0019:41:00","08:41:0020:23:00","13:28:0021:36:00","09:32:0020:42:00","09:27:0021:19:00","09:54:0021:45:00","10:03:0020:17:00","09:54:0019:11:00","09:37:0019:18:00","NA","NA","09:54:0021:23:00","09:43:0021:04:00","08:59:0020:46:00","09:51:0020:11:00","09:47:0018:57:00","08:50:0020:30:00","09:52:0022:44:00","09:16:0019:00:00","09:39:0020:37:00","09:49:0019:41:00","09:38:0020:29:00","07:53:0018:39:00","09:47:0020:31:00","09:54:0022:02:00","10:14:0024:00:00","09:53:0020:10:00","NA","09:51:0020:14:00","10:00:0020:00:00","08:21:0020:16:00","09:52:0020:37:00","09:53:0020:11:00","09:57:0022:01:00","09:53:0020:14:00","09:56:0022:00:00","NA","09:56:0019:15:00","NA","10:00:0021:09:00","09:27:0021:19:00","09:42:0021:45:00","NA","09:43:0019:30:00","09:40:0020:38:00","09:07:0019:43:00","09:53:0020:23:00","NA","09:24:0019:14:00","09:59:0019:10:00","09:53:0019:30:00","10:00:0020:51:00","09:42:0020:52:00","07:53:0020:28:00","09:24:0020:50:00","09:52:0020:53:00","09:21:0018:23:00","09:43:0019:29:00","09:59:0020:01:00","09:00:0020:01:00","09:41:0019:43:00","09:54:0020:10:00","09:59:0020:04:00","09:28:0020:09:00","09:50:0018:52:00","NA","09:56:0019:44:00","09:42:0018:48:00","09:42:0018:48:00","NA","09:22:0020:09:00","09:54:0020:14:00","09:46:0018:55:00","09:50:0020:25:00","10:00:0019:24:00","09:54:0020:38:00","09:52:0020:12:00","09:22:0018:38:00","09:52:0019:53:00","09:54:0020:12:00","09:28:0019:45:00","09:41:0020:24:00","09:37:0020:16:00","10:08:0020:55:00","09:40:0020:54:00","09:58:0020:48:00","NA","09:56:0009:57:00"
) %>% 
    as_tibble() %>% 
    filter(value!="NA") %>% 
    mutate_all(
    ~if_else(
          difftime(as.hms(str_sub(., 9, 16)), as.hms(str_sub(., 1, 8))) >= 10
      ,1, 0
    )
    )
```
